{% set python_min = "3.11" %}
{% set name = "brainglobe-atlasapi" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e398a9b240efdea738b172db62ccba67e5512eb5f6508c4aa5e977646a0ca07e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - brainglobe-space >=1.0.0
    - click
    - meshio
    - numpy
    - pandas
    - pyarrow
    - requests
    - rich >=9.0.0
    - tifffile
    - tqdm >=4.46.1
    - treelib
    - vtk

test:
  imports:
    - brainglobe_atlasapi
  commands:
    - pip check
    - brainglobe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brainglobe/brainglobe-atlasapi
  summary: A lightweight python module to interact with and generate atlases for systems neuroscience.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - alessandrofelder
